title: Talon for Dragon Users
author: Anders Schneiderman
email: your-email@domain.com
description:  Switching to Talon

# Menu data for sitewide navigation
navigation_links:
  - name: Setting Up
    link: 'about/'
  - name: Scripting
    link: 'pages/scripting/scripting-talon.html'
  # - name: Strategies
  #   link: 'strategies/'
  # # - name: Blog
  #   link: 'blog/'
  # # - name: Links
    # link: 'links'


